database_users_table_util/database_users_table_util.go
docs/database-users-table.md
handler/register_staff_handler.go
model/user.go
router/router.go

[Feature] Add APIs for staff registration.

---

README.md
docs/database-users-table.md

[Feature] Modify database users table documentation.

---

database_users_table_util/database_users_table_util.go

Fix Error 1049: Unknown database 'user_data'.

[Hotfix] Fix error occurred when creating the database users table.

---

database_users_table_util/database_users_table_util.go
database_util/database_util.go

Make the function `queryDatabase()` in the package `database_users_table_util` universal.

[Feature] Make queryDatabase() universal.

---

database_users_table_util/database_users_table_util.go
database_util/database_util.go

Make the function `CreateTableIfNotExists()` inside the package `database_users_table_util` universal.

[Feature] Make create table universal.

---

database/database.go
database/database_constant.go
database/mySql.go

[Feature] Database constant

---

middleware/middleware.go
router/router.go

[Feature] Add cors support

---

database/database.go
database/database_constant.go

- add_to_cart
- buy
- order_item
```
CartId
ProductId
Quantity
```
- customer_own_cart
```
CartId
CustomerId
```
- trade
```
CartId
ProductId
Quantity
DateTime
```

[Fix] Fix order-related table

---

app.go
database/customer_own_cart_operation.go
database/mySql.go
database/order_item_operation.go
handler/delete_order_item_in_cart_handler.go
handler/get_cart_id_with_username.go
router/router.go

- 在 appendRowsDataIntoTableData function 中，將 `tableData` 轉為 `pointer` 參數

[Fix] Fix get order items in cart

---

database/customer_own_cart_operation.go
database/order_item_operation.go
handler/delete_order_item_in_cart_handler.go
handler/get_cart_id_with_username.go
router/router.go

[Feature] Add customer own cart operation

---

app.go
database/customer_own_cart_operation.go
database/mySql.go
database/order_item_operation.go
handler/delete_order_item_in_cart_handler.go
handler/get_cart_id_with_username.go
router/router.go

[Fix] Fix get cart id with user name

---

app.go
database/buy.go
database/get_order.go
handler/buy_handler.go
handler/get_cart_id_with_username.go
handler/get_order_handler.go
router/router.go

set up transaction related api
currently cannot map query result to map

[Feature] Setup transaction

---

docs/database-buy.md

[Feature] Add doc for buy

---

database/add_cart_to_user.go
database/database.go
handler/get_cart_id_with_username.go
handler/sign_up_handler.go

[Fix] Fix sign up with cartId

---

database/get_staff_order.go
handler/get_staff_order_handler.go
router/router.go

[Feature] Add get staff order operation

---

middleware/middleware.go
router/router.go

change api endpoint, extend token expired date

[Hotfix] Api endpoint

---

database/staff_product_operation.go

目前是利用 product table 中 最大的 ProductId + 1，做為下一商品的 ProductId

[Fix] Add Product Sequential Product_ID

---

database/order_item_operation.go
handler/add_order_item_to_cart_handler.go

[Fix] Fix GetOrderItemsInCart/insert ProductId query

---

database/buy.go
database/database.go

[Fix] Fix delete order item cascade problem

---

docs/database-discount-policies-tables.md
handler/get_discount_policy_handler.go
router/router.go

Add API for getting a discount policy by code.

[Feature] Add API for getting a discount policy by code.

---

docs/database-discount-policies-tables.md
docs/database-users-table.md

Update the documentations of the database tables `users` and discount policies to include `/api` in their APIs' paths.

[Hotfix] Update the documentations of the database tables users and discount policies.

---

database/order_item_operation.go
handler/buy_handler.go

[Feature] Add discount code in GetOrderItemsInCart's return value

---

database/database.go

[Fix] Fix ProductId cascade

---

database/get_order.go
handler/get_order_handler.go
middleware/middleware.go

fix trade order, and add delete on cors

[HotFix] Trade order

---

database/buy.go

[Fix] Fix buy api with product quantity and inventory

---

database/get_staff_order.go

[FIx] Fix get staff order, order by datetime

---

database/database.go

Fix the foreign key (referential integrity) constraint violation issue when deleting a user.

[Hotfix] Fix referential integrity constraint violation when deleting a user.
